spring:
  cloud:
    stream:
      default:
        producer:
          headerMode: raw
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        leads-out:
          destination: topic-lead
          contentType: application/json
