security:
  oauth2:
    client:
      clientId: leadService
      clientSecret: ${LEAD_SERVICE_PASSWORD}
      accessTokenUri: 192.168.1.102:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server


server:
  port: 8899


spring:
  cloud:
    stream:
      default:
        producer:
          headerMode: raw
      kafka:
        binder:
          brokers: 192.168.1.102:9092
      bindings:
        leads-out:
          destination: topic-lead
          contentType: application/json